package Aplicativo;

import static Aplicativo.Arquivos.buscaExercicio;
import static Aplicativo.Arquivos.buscarDataTreino;
import static Aplicativo.Arquivos.caloriasTreino;
import static Aplicativo.Arquivos.capturarDados;
import static Aplicativo.Arquivos.dadosExercicios;
import static Aplicativo.Arquivos.dadosTreino;
import static Aplicativo.Arquivos.dadosUsuario;
import static Aplicativo.Arquivos.setStatusVisualizado;
import java.awt.Color;
import static java.awt.Color.white;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TelaIniciarTreino extends javax.swing.JFrame {

    /**
     * Creates new form TelaAbdomen
     */
    
    public TelaIniciarTreino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeAbdomen = new javax.swing.JLabel();
        nomeTreinoApp = new javax.swing.JLabel();
        treinoApp = new javax.swing.JButton();
        voltarApp = new javax.swing.JLabel();
        dataTreino = new javax.swing.JLabel();
        dataTreinoApp = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Treino");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(18, 18, 75));

        iconeAbdomen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeAbdomen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAbdominal.png"))); // NOI18N

        nomeTreinoApp.setBackground(new java.awt.Color(255, 255, 255));
        nomeTreinoApp.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        nomeTreinoApp.setForeground(new java.awt.Color(255, 255, 255));
        nomeTreinoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeTreinoApp.setText("Abdômen");
        nomeTreinoApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomeTreinoAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomeTreinoAppMouseExited(evt);
            }
        });

        treinoApp.setBackground(new java.awt.Color(218, 51, 104));
        treinoApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        treinoApp.setForeground(new java.awt.Color(255, 255, 255));
        treinoApp.setText("Iniciar Treino");
        treinoApp.setBorder(null);
        treinoApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        treinoApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                treinoAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                treinoAppMouseExited(evt);
            }
        });
        treinoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinoAppActionPerformed(evt);
            }
        });

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        dataTreino.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        dataTreino.setForeground(new java.awt.Color(255, 255, 255));
        dataTreino.setText("Data do Treino:");

        dataTreinoApp.setBackground(new java.awt.Color(255, 255, 255));
        dataTreinoApp.setForeground(new java.awt.Color(18, 18, 75));
        try {
            dataTreinoApp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataTreinoApp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataTreinoApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeAbdomen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeTreinoApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(treinoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(dataTreino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataTreinoApp)))
                .addGap(75, 75, 75))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(iconeAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTreinoApp)
                .addGap(18, 18, 18)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTreino, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(dataTreinoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(treinoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTreinoAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTreinoAppMouseEntered
        Color salmao = new Color(218,51,104);
        nomeTreinoApp.setForeground(salmao);
    }//GEN-LAST:event_nomeTreinoAppMouseEntered

    private void nomeTreinoAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTreinoAppMouseExited
        nomeTreinoApp.setForeground(white);
    }//GEN-LAST:event_nomeTreinoAppMouseExited

    private void treinoAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treinoAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        treinoApp.setForeground(rosaClaro);
        treinoApp.setBackground(white);
    }//GEN-LAST:event_treinoAppMouseEntered

    private void treinoAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treinoAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        treinoApp.setForeground(white);
        treinoApp.setBackground(rosaClaro);
    }//GEN-LAST:event_treinoAppMouseExited

    private void treinoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinoAppActionPerformed
        if(dataTreinoApp.getText().contains(" ")) {
            JOptionPane.showMessageDialog(null, "O campo data deve ser preenchido corretamente!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        TelaExercicio nova = new TelaExercicio();
        ImageIcon barraSuperior = new ImageIcon("src/Imagens/barraSuperior.png");
        // Identificação do treino
        String treino = nomeTreinoApp.getText();
        
        int i = buscarDataTreino(treino, dataTreinoApp.getText());
        if(i != -1) {
            JOptionPane.showMessageDialog(null, "O registro já contém um treino de "+treino+"\npara a data inserida!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LocalDate data1 = null;
        LocalDate data2 = null;
        
        String[] date1 = dataTreinoApp.getText().split("/"); 
        int dia1 = parseInt(date1[0]);
        int mes1 = parseInt(date1[1]);
        int ano1 = parseInt(date1[2]);
        
        try{
            data1 = LocalDate.of(ano1, mes1, dia1);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "O campo data deve ser preenchido corretamente!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        if(dadosTreino.isEmpty()){
            data2 = data1;
        }else{
            data2 = dadosTreino.get(0).getDate();
            for(Treino aux : dadosTreino){
                if(data2.compareTo(aux.getDate()) < 0){
                    data2 = aux.getDate();
                }
            }
        }
        
        if(data1.compareTo(data2) < 0){
            JOptionPane.showMessageDialog(null, "O registro contém uma data maior que a inserida!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String nivel = "Nivel: " + dadosUsuario.get(0).getCategoria();
        
        int j = buscaExercicio(treino); 
        ImageIcon imagemExercicio;
        
        switch (treino) {
            case "Abdômen":
                imagemExercicio = new ImageIcon("src/Imagens/toqueCalcanhar.gif");
                break;
            case "Peitoral":
                imagemExercicio = new ImageIcon("src/Imagens/flexaoInclinada.gif");
                break;
            case "Braços":
                imagemExercicio = new ImageIcon("src/Imagens/roscaBiceps.gif");
                break;
            case "Pernas":
                imagemExercicio = new ImageIcon("src/Imagens/agachamento.gif");
                break;
            default:
                imagemExercicio = new ImageIcon("src/Imagens/ombroHaltere.gif");
                break;
        }
        
        String nome = dadosExercicios.get(j).getNome(); // Pegar arquivo de exercícios
        String categoria = "Categoria: "+dadosExercicios.get(j).getGrupoMuscular(); // Pegar do arquivo de exercícios
        String repeticoes = "Número de repetições: "+dadosExercicios.get(j).getRepeticoes(); // Pegar do arquivo de exercícios
        String tempo = "Tempo: "+dadosExercicios.get(j).getTempo()+" minutos"; // Pegar do arquivo de exercícios
        String calorias = "Calorias gastas: "+dadosExercicios.get(j).getCalorias()+" kcal"; // Pegar do arquivo de exercicios
        nova.setParametrosInicio(nome, nivel, categoria, repeticoes, tempo, calorias,
                                 barraSuperior, imagemExercicio);
        
        setStatusVisualizado(j, true);
        
        capturarDados[0] = treino;
        capturarDados[1] = dataTreinoApp.getText();
        caloriasTreino = caloriasTreino + dadosExercicios.get(j).getCalorias();
        
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_treinoAppActionPerformed

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaTreino nova = new TelaTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited
    
    public void setParametros(String treino, ImageIcon icone){
        iconeAbdomen.setIcon(icone);
        nomeTreinoApp.setText(treino);
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIniciarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIniciarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIniciarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIniciarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIniciarTreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataTreino;
    private javax.swing.JFormattedTextField dataTreinoApp;
    private javax.swing.JLabel iconeAbdomen;
    private javax.swing.JLabel nomeTreinoApp;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JButton treinoApp;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}