/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Aplicativo;

import static Aplicativo.Arquivos.coletarCaloriasDieta;
import static Aplicativo.Arquivos.coletarCaloriasTreino;
import static Aplicativo.Arquivos.dadosUsuario;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */

public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorio
     */
    
    public TelaRelatorio() {
        initComponents();
        this.setLocationRelativeTo(null);
        painelInformacoes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeRelatorio = new javax.swing.JLabel();
        voltarApp = new javax.swing.JLabel();
        painelRelatorioApp = new javax.swing.JPanel();
        labelDataInicial = new javax.swing.JLabel();
        campoDataInicial = new javax.swing.JFormattedTextField();
        campoDataFinal = new javax.swing.JFormattedTextField();
        labelDataFinal = new javax.swing.JLabel();
        botaoOK = new javax.swing.JButton();
        painelInformacoes = new javax.swing.JPanel();
        campoCaloriasPerdidas = new javax.swing.JTextField();
        labelCaloriasPerdidas = new javax.swing.JLabel();
        campoCaloriasIngeridas = new javax.swing.JTextField();
        labelCaloriasIngeridas = new javax.swing.JLabel();
        labelAvaliacao = new javax.swing.JLabel();
        campoAvaliacao = new javax.swing.JTextField();
        campoIMC = new javax.swing.JTextField();
        labelIMC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Relatório");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));

        iconeRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeRelatorio.png"))); // NOI18N

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        painelRelatorioApp.setBackground(new java.awt.Color(255, 255, 255));
        painelRelatorioApp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans", 0, 12), new java.awt.Color(18, 18, 75))); // NOI18N

        labelDataInicial.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelDataInicial.setForeground(new java.awt.Color(18, 18, 75));
        labelDataInicial.setText("Data Inicial");

        campoDataInicial.setBackground(new java.awt.Color(255, 255, 255));
        campoDataInicial.setForeground(new java.awt.Color(18, 18, 75));
        try {
            campoDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        campoDataFinal.setBackground(new java.awt.Color(255, 255, 255));
        campoDataFinal.setForeground(new java.awt.Color(18, 18, 75));
        try {
            campoDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelDataFinal.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelDataFinal.setForeground(new java.awt.Color(18, 18, 75));
        labelDataFinal.setText("Data Final");

        botaoOK.setBackground(new java.awt.Color(218, 51, 104));
        botaoOK.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        botaoOK.setForeground(new java.awt.Color(255, 255, 255));
        botaoOK.setText("OK");
        botaoOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoOKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoOKMouseExited(evt);
            }
        });
        botaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRelatorioAppLayout = new javax.swing.GroupLayout(painelRelatorioApp);
        painelRelatorioApp.setLayout(painelRelatorioAppLayout);
        painelRelatorioAppLayout.setHorizontalGroup(
            painelRelatorioAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatorioAppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRelatorioAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(campoDataInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelRelatorioAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelRelatorioAppLayout.createSequentialGroup()
                        .addComponent(campoDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRelatorioAppLayout.setVerticalGroup(
            painelRelatorioAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatorioAppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRelatorioAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataInicial)
                    .addComponent(labelDataFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRelatorioAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelInformacoes.setBackground(new java.awt.Color(255, 255, 255));

        campoCaloriasPerdidas.setEditable(false);
        campoCaloriasPerdidas.setBackground(new java.awt.Color(255, 255, 255));
        campoCaloriasPerdidas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        labelCaloriasPerdidas.setBackground(new java.awt.Color(255, 255, 255));
        labelCaloriasPerdidas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelCaloriasPerdidas.setForeground(new java.awt.Color(18, 18, 75));
        labelCaloriasPerdidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCaloriasPerdidas.setText("Calorias perdidas");

        campoCaloriasIngeridas.setEditable(false);
        campoCaloriasIngeridas.setBackground(new java.awt.Color(255, 255, 255));
        campoCaloriasIngeridas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        labelCaloriasIngeridas.setBackground(new java.awt.Color(255, 255, 255));
        labelCaloriasIngeridas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelCaloriasIngeridas.setForeground(new java.awt.Color(18, 18, 75));
        labelCaloriasIngeridas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCaloriasIngeridas.setText("Calorias ingeridas");

        labelAvaliacao.setBackground(new java.awt.Color(255, 255, 255));
        labelAvaliacao.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelAvaliacao.setForeground(new java.awt.Color(18, 18, 75));
        labelAvaliacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAvaliacao.setText("Avaliação");

        campoAvaliacao.setEditable(false);
        campoAvaliacao.setBackground(new java.awt.Color(255, 255, 255));
        campoAvaliacao.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        campoIMC.setEditable(false);
        campoIMC.setBackground(new java.awt.Color(255, 255, 255));
        campoIMC.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        labelIMC.setBackground(new java.awt.Color(255, 255, 255));
        labelIMC.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelIMC.setForeground(new java.awt.Color(18, 18, 75));
        labelIMC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIMC.setText("IMC");

        javax.swing.GroupLayout painelInformacoesLayout = new javax.swing.GroupLayout(painelInformacoes);
        painelInformacoes.setLayout(painelInformacoesLayout);
        painelInformacoesLayout.setHorizontalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCaloriasPerdidas)
                    .addComponent(labelCaloriasPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCaloriasIngeridas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCaloriasIngeridas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addComponent(campoAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(campoIMC))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInformacoesLayout.createSequentialGroup()
                .addComponent(labelAvaliacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(labelIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelInformacoesLayout.setVerticalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaloriasPerdidas)
                    .addComponent(labelCaloriasIngeridas, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCaloriasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCaloriasIngeridas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAvaliacao)
                    .addComponent(labelIMC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelRelatorioApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(iconeRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelRelatorioApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaSelecao nova = new TelaSelecao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited

    private void botaoOKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoOKMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoOK.setForeground(rosaClaro);
        botaoOK.setBackground(white);
    }//GEN-LAST:event_botaoOKMouseEntered

    private void botaoOKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoOKMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoOK.setForeground(white);
        botaoOK.setBackground(rosaClaro);
    }//GEN-LAST:event_botaoOKMouseExited

    private void botaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOKActionPerformed
        if(campoDataInicial.getText().contains(" ") || campoDataFinal.getText().contains(" ")) {
            JOptionPane.showMessageDialog(null, "Os campos de data devem ser\n preenchidos corretamente!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String[] date1 = campoDataInicial.getText().split("/"); 
        int dia1 = parseInt(date1[0]);
        int mes1 = parseInt(date1[1]);
        int ano1 = parseInt(date1[2]);
        
        String[] date2 = campoDataFinal.getText().split("/"); 
        int dia2 = parseInt(date2[0]);
        int mes2 = parseInt(date2[1]);
        int ano2 = parseInt(date2[2]);
     
        LocalDate dataInicial = null;
        LocalDate dataFinal = null;
        
        try{
            dataInicial = LocalDate.of(ano1, mes1, dia1);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data inicial preenchida incorretamente!",
                                          "Erro Data", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            dataFinal = LocalDate.of(ano2, mes2, dia2);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data final preenchida incorretamente!",
                                          "Erro Data", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int verificaData = dataFinal.compareTo(dataInicial);
        
        if(verificaData < 0){
            JOptionPane.showMessageDialog(null, "Data inicial deve ser\n anteriar a data final!",
                                          "Erro Data", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double caloriasTreino = coletarCaloriasTreino(campoDataInicial.getText(), campoDataFinal.getText());
        double caloriasDieta = coletarCaloriasDieta(campoDataInicial.getText(), campoDataFinal.getText());
        double imc = dadosUsuario.get(0).getPeso() / Math.pow((dadosUsuario.get(0).getAltura()/100),2);
        
        String avaliacao;
        if(imc < 18.5) {
            avaliacao = "Abaixo do peso";
        } else if(imc < 24.9){
            avaliacao = "Peso normal";
        } else if(imc < 29.9) {
            avaliacao = "Sobrepeso";
        } else if(imc < 34.9) {
            avaliacao = "Obesidade grau 1";
        } else if(imc < 39.9){
            avaliacao = "Obesidade grau 2";
        } else {
            avaliacao = "Obesidade morbida";
        }
        
        painelInformacoes.setVisible(true);
        campoCaloriasPerdidas.setText(Double.toString(caloriasTreino));
        campoCaloriasIngeridas.setText(Double.toString(caloriasDieta));
        campoAvaliacao.setText(avaliacao);
        campoIMC.setText(String.format("%.2f", imc)); 
    }//GEN-LAST:event_botaoOKActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOK;
    private javax.swing.JTextField campoAvaliacao;
    private javax.swing.JTextField campoCaloriasIngeridas;
    private javax.swing.JTextField campoCaloriasPerdidas;
    private javax.swing.JFormattedTextField campoDataFinal;
    private javax.swing.JFormattedTextField campoDataInicial;
    private javax.swing.JTextField campoIMC;
    private javax.swing.JLabel iconeRelatorio;
    private javax.swing.JLabel labelAvaliacao;
    private javax.swing.JLabel labelCaloriasIngeridas;
    private javax.swing.JLabel labelCaloriasPerdidas;
    private javax.swing.JLabel labelDataFinal;
    private javax.swing.JLabel labelDataInicial;
    private javax.swing.JLabel labelIMC;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelInformacoes;
    private javax.swing.JPanel painelRelatorioApp;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}
