package Aplicativo;

import static Aplicativo.Arquivos.capturarDados;
import static Aplicativo.Arquivos.escreverArquivoDieta;
import static Aplicativo.Arquivos.salvarDadosDieta;
import java.awt.Color;
import static java.lang.Double.parseDouble;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TelaAlimentos extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlimentos
     */
    
    public TelaAlimentos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeAlimentosApp = new javax.swing.JLabel();
        labelAlimentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoApp = new javax.swing.JTextArea();
        labelCalorias = new javax.swing.JLabel();
        caloriasApp = new javax.swing.JFormattedTextField();
        salvarAlimentosApp = new javax.swing.JButton();
        voltarApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));

        iconeAlimentosApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAlimentos.png"))); // NOI18N

        labelAlimentos.setBackground(new java.awt.Color(255, 255, 255));
        labelAlimentos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelAlimentos.setForeground(new java.awt.Color(18, 18, 75));
        labelAlimentos.setText("Alimentos da refeição");

        descricaoApp.setBackground(new java.awt.Color(255, 255, 255));
        descricaoApp.setColumns(20);
        descricaoApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        descricaoApp.setForeground(new java.awt.Color(18, 18, 75));
        descricaoApp.setLineWrap(true);
        descricaoApp.setRows(5);
        descricaoApp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(descricaoApp);

        labelCalorias.setBackground(new java.awt.Color(255, 255, 255));
        labelCalorias.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelCalorias.setForeground(new java.awt.Color(18, 18, 75));
        labelCalorias.setText("Total de calorias da refeição");

        caloriasApp.setBackground(new java.awt.Color(255, 255, 255));
        caloriasApp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        caloriasApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        salvarAlimentosApp.setBackground(new java.awt.Color(218, 51, 104));
        salvarAlimentosApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        salvarAlimentosApp.setForeground(new java.awt.Color(255, 255, 255));
        salvarAlimentosApp.setText("Salvar");
        salvarAlimentosApp.setBorder(null);
        salvarAlimentosApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvarAlimentosApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarAlimentosAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarAlimentosAppMouseExited(evt);
            }
        });
        salvarAlimentosApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAlimentosAppActionPerformed(evt);
            }
        });

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeAlimentosApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvarAlimentosApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelAlimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(labelCalorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caloriasApp)))
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(iconeAlimentosApp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caloriasApp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(salvarAlimentosApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarAlimentosAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarAlimentosAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        salvarAlimentosApp.setForeground(rosaClaro);
        salvarAlimentosApp.setBackground(white);
    }//GEN-LAST:event_salvarAlimentosAppMouseEntered

    private void salvarAlimentosAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarAlimentosAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        salvarAlimentosApp.setForeground(white);
        salvarAlimentosApp.setBackground(rosaClaro);
    }//GEN-LAST:event_salvarAlimentosAppMouseExited

    private void salvarAlimentosAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAlimentosAppActionPerformed
        if(descricaoApp.getText().isBlank() || caloriasApp.getText().isBlank() ||
           Double.parseDouble(caloriasApp.getText()) < 0){
            JOptionPane.showMessageDialog(null, "Campos preenchidos incorretamente!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(descricaoApp.getText().contains(";")){
            JOptionPane.showMessageDialog(null, "O campo alimentos não pode conter (;)!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        salvarDadosDieta(capturarDados[0], descricaoApp.getText(), capturarDados[1], parseDouble(caloriasApp.getText()));
        escreverArquivoDieta("DadosDieta.txt");
        
        TelaAlimentacao nova = new TelaAlimentacao();
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_salvarAlimentosAppActionPerformed

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaAlimentacao nova = new TelaAlimentacao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited
    
    public void setParametros(ImageIcon icone, String labelSuperior, String labelInferior){
        iconeAlimentosApp.setIcon(icone);
        labelAlimentos.setText(labelSuperior);
        labelCalorias.setText(labelInferior);
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField caloriasApp;
    private javax.swing.JTextArea descricaoApp;
    private javax.swing.JLabel iconeAlimentosApp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlimentos;
    private javax.swing.JLabel labelCalorias;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JButton salvarAlimentosApp;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}
