package Aplicativo;

import static Aplicativo.Arquivos.dadosUsuario;
import static Aplicativo.Arquivos.escreverArquivoUsuario;
import static Aplicativo.Arquivos.salvarDadosUsuario;
import java.awt.Color;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

public class TelaAtualizarDados extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtulizarDados
     */
    
    public TelaAtualizarDados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        labelPerfil = new javax.swing.JLabel();
        painelPerfil = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelIdade = new javax.swing.JLabel();
        campoIdade = new javax.swing.JFormattedTextField();
        labelPeso = new javax.swing.JLabel();
        campoPeso = new javax.swing.JTextField();
        labelAltura = new javax.swing.JLabel();
        campoAltura = new javax.swing.JFormattedTextField();
        labelSexo = new javax.swing.JLabel();
        boxSexo = new javax.swing.JComboBox<>();
        labelCategoria = new javax.swing.JLabel();
        boxCategoria = new javax.swing.JComboBox<>();
        salvarPerfilApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Atualizar Cadastro");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));

        labelPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconePerfil.png"))); // NOI18N

        painelPerfil.setBackground(new java.awt.Color(255, 255, 255));
        painelPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans", 0, 12), new java.awt.Color(18, 18, 75))); // NOI18N

        labelNome.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelNome.setForeground(new java.awt.Color(18, 18, 75));
        labelNome.setText("Nome:");

        campoNome.setBackground(new java.awt.Color(255, 255, 255));
        campoNome.setForeground(new java.awt.Color(18, 18, 75));

        labelIdade.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelIdade.setForeground(new java.awt.Color(18, 18, 75));
        labelIdade.setText("Idade:");

        campoIdade.setBackground(new java.awt.Color(255, 255, 255));
        campoIdade.setForeground(new java.awt.Color(18, 18, 75));
        try {
            campoIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelPeso.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelPeso.setForeground(new java.awt.Color(18, 18, 75));
        labelPeso.setText("Peso (kg):");

        campoPeso.setBackground(new java.awt.Color(255, 255, 255));
        campoPeso.setForeground(new java.awt.Color(18, 18, 75));

        labelAltura.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelAltura.setForeground(new java.awt.Color(18, 18, 75));
        labelAltura.setText("Altura (cm):");

        campoAltura.setBackground(new java.awt.Color(255, 255, 255));
        campoAltura.setForeground(new java.awt.Color(18, 18, 75));
        try {
            campoAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelSexo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelSexo.setForeground(new java.awt.Color(18, 18, 75));
        labelSexo.setText("Sexo:");

        boxSexo.setBackground(new java.awt.Color(255, 255, 255));
        boxSexo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        boxSexo.setForeground(new java.awt.Color(18, 18, 75));
        boxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        boxSexo.setMinimumSize(new java.awt.Dimension(56, 30));

        labelCategoria.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(18, 18, 75));
        labelCategoria.setText("Categoria:");

        boxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        boxCategoria.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        boxCategoria.setForeground(new java.awt.Color(18, 18, 75));
        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Iniciante", "Intermediário", "Avançado" }));
        boxCategoria.setMinimumSize(new java.awt.Dimension(56, 30));

        javax.swing.GroupLayout painelPerfilLayout = new javax.swing.GroupLayout(painelPerfil);
        painelPerfil.setLayout(painelPerfilLayout);
        painelPerfilLayout.setHorizontalGroup(
            painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(boxSexo, 0, 150, Short.MAX_VALUE)
                    .addComponent(labelSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPeso)
                    .addComponent(labelPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoNome, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(labelAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(campoAltura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxCategoria, 0, 150, Short.MAX_VALUE)
                    .addComponent(campoIdade))
                .addContainerGap())
        );
        painelPerfilLayout.setVerticalGroup(
            painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(campoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(labelAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(campoAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(labelCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        salvarPerfilApp.setBackground(new java.awt.Color(218, 51, 104));
        salvarPerfilApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        salvarPerfilApp.setForeground(new java.awt.Color(255, 255, 255));
        salvarPerfilApp.setText("Salvar");
        salvarPerfilApp.setBorder(null);
        salvarPerfilApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarPerfilAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarPerfilAppMouseExited(evt);
            }
        });
        salvarPerfilApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPerfilAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(painelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvarPerfilApp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addComponent(labelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(salvarPerfilApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarPerfilAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPerfilAppActionPerformed
        String nome = campoNome.getText();
        String idade = campoIdade.getText();
        String peso = campoPeso.getText();
        String altura = campoAltura.getText();
        String sexo = boxSexo.getSelectedItem().toString();
        String categoria = boxCategoria.getSelectedItem().toString();
        
        if(nome.isBlank() || idade.isBlank() ||
           peso.isBlank() || altura.contains(" ") ||
           sexo.equals("Selecione") || categoria.equals("Selecione") ||
           Double.parseDouble(peso) < 0) {
            JOptionPane.showMessageDialog(null, "Um dos campos está vazio ou\n não foi preenchido corretamente",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!dadosUsuario.isEmpty())
            dadosUsuario.remove(0);
        
        salvarDadosUsuario(nome, parseInt(idade), parseDouble(peso), parseDouble(altura), sexo, categoria);
        escreverArquivoUsuario("DadosUsuario.txt");
        
        TelaSelecao nova = new TelaSelecao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_salvarPerfilAppActionPerformed

    private void salvarPerfilAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarPerfilAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        salvarPerfilApp.setForeground(rosaClaro);
        salvarPerfilApp.setBackground(white);
    }//GEN-LAST:event_salvarPerfilAppMouseEntered

    private void salvarPerfilAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarPerfilAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        salvarPerfilApp.setForeground(white);
        salvarPerfilApp.setBackground(rosaClaro);
    }//GEN-LAST:event_salvarPerfilAppMouseExited
    
    public void mostrarDadosUsuario(String nome, String idade, String peso, String altura,
                                    String sexo, String categoria) {
        campoNome.setText(nome);
        campoIdade.setText(idade);
        campoPeso.setText(peso);
        campoAltura.setText(altura);
        boxSexo.setSelectedItem(sexo);
        boxCategoria.setSelectedItem(categoria);
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JComboBox<String> boxSexo;
    private javax.swing.JFormattedTextField campoAltura;
    private javax.swing.JFormattedTextField campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPerfil;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelPerfil;
    private javax.swing.JButton salvarPerfilApp;
    // End of variables declaration//GEN-END:variables
}
