package Aplicativo;

import static Aplicativo.Arquivos.buscaExercicio;
import static Aplicativo.Arquivos.caloriasTreino;
import static Aplicativo.Arquivos.capturarDados;
import static Aplicativo.Arquivos.dadosExercicios;
import static Aplicativo.Arquivos.dadosUsuario;
import static Aplicativo.Arquivos.escreverArquivoTreino;
import static Aplicativo.Arquivos.salvarDadosTreino;
import static Aplicativo.Arquivos.setStatusFalse;
import static Aplicativo.Arquivos.setStatusVisualizado;
import java.awt.Color;
import javax.swing.ImageIcon;

public class TelaExercicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaExercicio
     */
    
    public TelaExercicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraSuperiorApp = new javax.swing.JLabel();
        exercicioGIF = new javax.swing.JLabel();
        nivelApp = new javax.swing.JLabel();
        repeticoesApp = new javax.swing.JLabel();
        tempoApp = new javax.swing.JLabel();
        caloriasApp = new javax.swing.JLabel();
        nomeExercicioApp = new javax.swing.JLabel();
        proximoExercicioApp = new javax.swing.JButton();
        categoriaApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Exercício");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        barraSuperiorApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraSuperiorApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/barraSuperior.png"))); // NOI18N

        exercicioGIF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exercicioGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/toqueCalcanhar.gif"))); // NOI18N

        nivelApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        nivelApp.setForeground(new java.awt.Color(18, 18, 75));
        nivelApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelApp.setText("Nivel: Básico");

        repeticoesApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        repeticoesApp.setForeground(new java.awt.Color(18, 18, 75));
        repeticoesApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        repeticoesApp.setText("Número de Repetições: 10");

        tempoApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tempoApp.setForeground(new java.awt.Color(18, 18, 75));
        tempoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tempoApp.setText("Tempo: 2 minutos");

        caloriasApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        caloriasApp.setForeground(new java.awt.Color(18, 18, 75));
        caloriasApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caloriasApp.setText("Calorias gastas: 100 kcal");

        nomeExercicioApp.setBackground(new java.awt.Color(255, 255, 255));
        nomeExercicioApp.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        nomeExercicioApp.setForeground(new java.awt.Color(18, 18, 75));
        nomeExercicioApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeExercicioApp.setText("Toque de Calcanhar");
        nomeExercicioApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomeExercicioAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomeExercicioAppMouseExited(evt);
            }
        });

        proximoExercicioApp.setBackground(new java.awt.Color(218, 51, 104));
        proximoExercicioApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        proximoExercicioApp.setForeground(new java.awt.Color(255, 255, 255));
        proximoExercicioApp.setText("Próximo Exercício");
        proximoExercicioApp.setBorder(null);
        proximoExercicioApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proximoExercicioApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proximoExercicioAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proximoExercicioAppMouseExited(evt);
            }
        });
        proximoExercicioApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoExercicioAppActionPerformed(evt);
            }
        });

        categoriaApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        categoriaApp.setForeground(new java.awt.Color(18, 18, 75));
        categoriaApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoriaApp.setText("Categoria: Abdômen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraSuperiorApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(proximoExercicioApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exercicioGIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nivelApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(repeticoesApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempoApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caloriasApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeExercicioApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriaApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(barraSuperiorApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exercicioGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(nomeExercicioApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nivelApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeticoesApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempoApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caloriasApp)
                .addGap(28, 28, 28)
                .addComponent(proximoExercicioApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeExercicioAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeExercicioAppMouseEntered
        Color salmao = new Color(218,51,104);
        nomeExercicioApp.setForeground(salmao);
    }//GEN-LAST:event_nomeExercicioAppMouseEntered

    private void nomeExercicioAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeExercicioAppMouseExited
        Color azulEscuro = new Color(18,18,75);
        nomeExercicioApp.setForeground(azulEscuro);
    }//GEN-LAST:event_nomeExercicioAppMouseExited

    private void proximoExercicioAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proximoExercicioAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        proximoExercicioApp.setForeground(rosaClaro);
        proximoExercicioApp.setBackground(white);
    }//GEN-LAST:event_proximoExercicioAppMouseEntered

    private void proximoExercicioAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proximoExercicioAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        proximoExercicioApp.setForeground(white);
        proximoExercicioApp.setBackground(rosaClaro);
    }//GEN-LAST:event_proximoExercicioAppMouseExited

    private void proximoExercicioAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoExercicioAppActionPerformed
        String valorCategoria = categoriaApp.getText();
        String valores[] = valorCategoria.split(": ");
        String treino = valores[1];
        ImageIcon barraSuperior = new ImageIcon("src/Imagens/barraSuperior.png");
        String nivel = "Nivel: " + dadosUsuario.get(0).getCategoria();
        
        int j = buscaExercicio(treino);
        ImageIcon imagemExercicio = null;
        
        if(j == -1){
            salvarDadosTreino(capturarDados[0], capturarDados[1], caloriasTreino);
            escreverArquivoTreino("DadosTreino.txt");
            
            caloriasTreino = 0;
            setStatusFalse(treino);
            
            TelaTreino novaTela = new TelaTreino();
            novaTela.setLocationRelativeTo(null);
            novaTela.setVisible(true);
            dispose();
            
            return;
        }
        
        switch (treino) {
            case "Abdômen":
                imagemExercicio = new ImageIcon("src/Imagens/pranchaLateral.gif");
                break;
            case "Peitoral":
                imagemExercicio = new ImageIcon("src/Imagens/supinoHaltere.gif");
                break;
            case "Braços":
                imagemExercicio = new ImageIcon("src/Imagens/afundarTriceps.gif");
                break;
            case "Pernas":
                imagemExercicio = new ImageIcon("src/Imagens/agachamentoAfundo.gif");
                break;
            default:
                imagemExercicio = new ImageIcon("src/Imagens/levantarHalteres.gif");
                break;
        }
        
        TelaExercicio nova = new TelaExercicio();
        
        String nome = dadosExercicios.get(j).getNome(); // Pegar arquivo de exercícios
        String categoria = "Categoria: "+dadosExercicios.get(j).getGrupoMuscular(); // Pegar do arquivo de exercícios
        String repeticoes = "Número de repetições: "+dadosExercicios.get(j).getRepeticoes(); // Pegar do arquivo de exercícios
        String tempo = "Tempo: "+dadosExercicios.get(j).getTempo()+" minutos"; // Pegar do arquivo de exercícios
        String calorias = "Calorias gastas: "+dadosExercicios.get(j).getCalorias()+" kcal"; // Pegar do arquivo de exercicios
        nova.setParametrosNext(nome, nivel, categoria, repeticoes, tempo, calorias,
                               barraSuperior, imagemExercicio);
        setStatusVisualizado(j, true);
        
        caloriasTreino = caloriasTreino + dadosExercicios.get(j).getCalorias();
        
        String textoBotao = proximoExercicioApp.getText();
        if(textoBotao.equals("Próximo Exercício")){
            nova.setLocationRelativeTo(null);
            nova.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_proximoExercicioAppActionPerformed
    
    public void setParametrosInicio(String nomeExercicio, String nivel, String categoria,
                                    String repeticoes, String tempo, String calorias,
                                    ImageIcon barraSuperior, ImageIcon exercicio){
        nomeExercicioApp.setText(nomeExercicio);
        nivelApp.setText(nivel);
        categoriaApp.setText(categoria);
        repeticoesApp.setText(repeticoes);
        tempoApp.setText(tempo);
        caloriasApp.setText(calorias);
        barraSuperiorApp.setIcon(barraSuperior);
        exercicioGIF.setIcon(exercicio);
    }
    
    public void setParametrosNext(String nomeExercicio, String nivel, String categoria,
                                  String repeticoes, String tempo, String calorias,
                                  ImageIcon barraSuperior, ImageIcon exercicio){
        nomeExercicioApp.setText(nomeExercicio);
        nivelApp.setText(nivel);
        categoriaApp.setText(categoria);
        repeticoesApp.setText(repeticoes);
        tempoApp.setText(tempo);
        caloriasApp.setText(calorias);
        barraSuperiorApp.setIcon(barraSuperior);
        exercicioGIF.setIcon(exercicio);
        proximoExercicioApp.setText("Finalizar Treino");
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraSuperiorApp;
    private javax.swing.JLabel caloriasApp;
    private javax.swing.JLabel categoriaApp;
    private javax.swing.JLabel exercicioGIF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nivelApp;
    private javax.swing.JLabel nomeExercicioApp;
    private javax.swing.JButton proximoExercicioApp;
    private javax.swing.JLabel repeticoesApp;
    private javax.swing.JLabel tempoApp;
    // End of variables declaration//GEN-END:variables
}
