package Aplicativo;

import java.awt.Color;
import static java.awt.Color.white;

public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        facebook = new javax.swing.JLabel();
        instagram = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        logoApp = new javax.swing.JLabel();
        nomeApp = new javax.swing.JLabel();
        mensagemCima = new javax.swing.JLabel();
        mensagemBaixo = new javax.swing.JLabel();
        iniciarApp = new javax.swing.JButton();
        encerrarApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Fitness POO");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(18, 18, 75));

        facebook.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        facebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/facebook.png"))); // NOI18N
        facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
        });

        instagram.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        instagram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/instagram.png"))); // NOI18N
        instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramMouseClicked(evt);
            }
        });

        twitter.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        twitter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/twitter.png"))); // NOI18N
        twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
        });

        logoApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        logoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconePrograma.png"))); // NOI18N

        nomeApp.setBackground(new java.awt.Color(255, 255, 255));
        nomeApp.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        nomeApp.setForeground(new java.awt.Color(255, 255, 255));
        nomeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeApp.setText("My Fitness POO");
        nomeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomeAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomeAppMouseExited(evt);
            }
        });

        mensagemCima.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        mensagemCima.setForeground(new java.awt.Color(255, 255, 255));
        mensagemCima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagemCima.setText("Para tornar a sua vida mais saudável,");

        mensagemBaixo.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        mensagemBaixo.setForeground(new java.awt.Color(255, 255, 255));
        mensagemBaixo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagemBaixo.setText("dê o primeiro passo em rumo ao sucesso.");

        iniciarApp.setBackground(new java.awt.Color(218, 51, 104));
        iniciarApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        iniciarApp.setForeground(new java.awt.Color(255, 255, 255));
        iniciarApp.setText("Iniciar App");
        iniciarApp.setBorder(null);
        iniciarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarAppMouseExited(evt);
            }
        });
        iniciarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarAppActionPerformed(evt);
            }
        });

        encerrarApp.setBackground(new java.awt.Color(218, 51, 104));
        encerrarApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        encerrarApp.setForeground(new java.awt.Color(255, 255, 255));
        encerrarApp.setText("Encerrar");
        encerrarApp.setBorder(null);
        encerrarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encerrarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encerrarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encerrarAppMouseExited(evt);
            }
        });
        encerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(facebook)
                        .addGap(82, 82, 82)
                        .addComponent(instagram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twitter)))
                .addGap(70, 70, 70))
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensagemBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensagemCima, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(iniciarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encerrarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addComponent(logoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeApp)
                .addGap(18, 18, 18)
                .addComponent(mensagemCima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagemBaixo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encerrarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facebook)
                    .addComponent(instagram)
                    .addComponent(twitter))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        // COLOCAR LINK DO FACEBOOK DA EMPRESA
    }//GEN-LAST:event_facebookMouseClicked

    private void instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseClicked
        // COLOCAR LINK DO INSTAGRAM DA EMPRESA
    }//GEN-LAST:event_instagramMouseClicked

    private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
        // COLOCAR LINK DO TWITTER DA EMPRESA
    }//GEN-LAST:event_twitterMouseClicked

    private void nomeAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeAppMouseEntered
        Color salmao = new Color(218,51,104);
        nomeApp.setForeground(salmao);
    }//GEN-LAST:event_nomeAppMouseEntered

    private void nomeAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeAppMouseExited
         nomeApp.setForeground(white);
    }//GEN-LAST:event_nomeAppMouseExited

    private void iniciarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarAppActionPerformed
        setVisible(false);
        TelaSelecao nova = new TelaSelecao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_iniciarAppActionPerformed

    private void iniciarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        iniciarApp.setForeground(rosaClaro);
        iniciarApp.setBackground(white);
    }//GEN-LAST:event_iniciarAppMouseEntered

    private void iniciarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        iniciarApp.setForeground(white);
        iniciarApp.setBackground(rosaClaro);
    }//GEN-LAST:event_iniciarAppMouseExited

    private void encerrarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encerrarAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        encerrarApp.setForeground(rosaClaro);
        encerrarApp.setBackground(white);
    }//GEN-LAST:event_encerrarAppMouseEntered

    private void encerrarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encerrarAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        encerrarApp.setForeground(white);
        encerrarApp.setBackground(rosaClaro);
    }//GEN-LAST:event_encerrarAppMouseExited

    private void encerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_encerrarAppActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encerrarApp;
    private javax.swing.JLabel facebook;
    private javax.swing.JButton iniciarApp;
    private javax.swing.JLabel instagram;
    private javax.swing.JLabel logoApp;
    private javax.swing.JLabel mensagemBaixo;
    private javax.swing.JLabel mensagemCima;
    private javax.swing.JLabel nomeApp;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JLabel twitter;
    // End of variables declaration//GEN-END:variables
}
