package Aplicativo;

import static Aplicativo.Arquivos.dadosDieta;
import static Aplicativo.Arquivos.dadosExercicios;
import static Aplicativo.Arquivos.dadosTreino;
import static Aplicativo.Arquivos.dadosUsuario;
import static Aplicativo.Arquivos.lerArquivo;
import static Aplicativo.Arquivos.preencherDadosDieta;
import static Aplicativo.Arquivos.preencherDadosExercicios;
import static Aplicativo.Arquivos.preencherDadosTreino;
import static Aplicativo.Arquivos.preencherDadosUsuario;
import java.awt.Color;
import javax.swing.ImageIcon;

public class TelaSelecao extends javax.swing.JFrame {

    /**
     * Creates new form TelaSelecao
     */
    
    public TelaSelecao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeInicio = new javax.swing.JLabel();
        treinoApp = new javax.swing.JButton();
        alimentacaoApp = new javax.swing.JButton();
        relatorioApp = new javax.swing.JButton();
        voltarApp = new javax.swing.JLabel();
        atualizarDadosApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("My Fitness POO");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));

        iconeInicio.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        iconeInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeInicio.png"))); // NOI18N

        treinoApp.setBackground(new java.awt.Color(218, 51, 104));
        treinoApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        treinoApp.setForeground(new java.awt.Color(255, 255, 255));
        treinoApp.setText("Treino");
        treinoApp.setBorder(null);
        treinoApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        treinoApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                treinoAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                treinoAppMouseExited(evt);
            }
        });
        treinoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinoAppActionPerformed(evt);
            }
        });

        alimentacaoApp.setBackground(new java.awt.Color(218, 51, 104));
        alimentacaoApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        alimentacaoApp.setForeground(new java.awt.Color(255, 255, 255));
        alimentacaoApp.setText("Alimentação");
        alimentacaoApp.setBorder(null);
        alimentacaoApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alimentacaoApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alimentacaoAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alimentacaoAppMouseExited(evt);
            }
        });
        alimentacaoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentacaoAppActionPerformed(evt);
            }
        });

        relatorioApp.setBackground(new java.awt.Color(218, 51, 104));
        relatorioApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        relatorioApp.setForeground(new java.awt.Color(255, 255, 255));
        relatorioApp.setText("Relatório");
        relatorioApp.setBorder(null);
        relatorioApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relatorioApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                relatorioAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                relatorioAppMouseExited(evt);
            }
        });
        relatorioApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioAppActionPerformed(evt);
            }
        });

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        atualizarDadosApp.setBackground(new java.awt.Color(218, 51, 104));
        atualizarDadosApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        atualizarDadosApp.setForeground(new java.awt.Color(255, 255, 255));
        atualizarDadosApp.setText("Atualizar dados");
        atualizarDadosApp.setBorder(null);
        atualizarDadosApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizarDadosApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atualizarDadosAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atualizarDadosAppMouseExited(evt);
            }
        });
        atualizarDadosApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarDadosAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atualizarDadosApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relatorioApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alimentacaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treinoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(iconeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treinoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alimentacaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(relatorioApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizarDadosApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaInicial nova = new TelaInicial();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void treinoAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treinoAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        treinoApp.setForeground(rosaClaro);
        treinoApp.setBackground(white);
    }//GEN-LAST:event_treinoAppMouseEntered

    private void treinoAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treinoAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        treinoApp.setForeground(white);
        treinoApp.setBackground(rosaClaro);
    }//GEN-LAST:event_treinoAppMouseExited

    private void alimentacaoAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alimentacaoAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        alimentacaoApp.setForeground(rosaClaro);
        alimentacaoApp.setBackground(white);
    }//GEN-LAST:event_alimentacaoAppMouseEntered

    private void alimentacaoAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alimentacaoAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        alimentacaoApp.setForeground(white);
        alimentacaoApp.setBackground(rosaClaro);
    }//GEN-LAST:event_alimentacaoAppMouseExited

    private void relatorioAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        relatorioApp.setForeground(rosaClaro);
        relatorioApp.setBackground(white);
    }//GEN-LAST:event_relatorioAppMouseEntered

    private void relatorioAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        relatorioApp.setForeground(white);
        relatorioApp.setBackground(rosaClaro);
    }//GEN-LAST:event_relatorioAppMouseExited

    private void atualizarDadosAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarDadosAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        atualizarDadosApp.setForeground(rosaClaro);
        atualizarDadosApp.setBackground(white);
    }//GEN-LAST:event_atualizarDadosAppMouseEntered

    private void atualizarDadosAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarDadosAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        atualizarDadosApp.setForeground(white);
        atualizarDadosApp.setBackground(rosaClaro);
    }//GEN-LAST:event_atualizarDadosAppMouseExited

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited

    private void atualizarDadosAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarDadosAppActionPerformed
        if(dadosUsuario.isEmpty()){ 
            preencherDadosUsuario();
        }else{
            lerArquivo("DadosUsuario.txt");
        }
        
        TelaAtualizarDados nova = new TelaAtualizarDados();
        if(!dadosUsuario.isEmpty()) {
            String nome = dadosUsuario.get(0).getNome();
            String idade = Integer.toString(dadosUsuario.get(0).getIdade());
            String peso = Double.toString(dadosUsuario.get(0).getPeso());
            String altura = Double.toString(dadosUsuario.get(0).getAltura());
            String sexo = dadosUsuario.get(0).getSexo();
            String categoria = dadosUsuario.get(0).getCategoria();

            nova.mostrarDadosUsuario(nome, idade, peso, altura, sexo, categoria);
        }
        
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_atualizarDadosAppActionPerformed

    private void treinoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinoAppActionPerformed
        if(dadosTreino.isEmpty())
            preencherDadosTreino();
        else
            lerArquivo("DadosTreino.txt");
        
        if(dadosUsuario.isEmpty())
            preencherDadosUsuario();
        else
            lerArquivo("DadosUsuario.txt");
        
        if(dadosExercicios.isEmpty())
            preencherDadosExercicios();
        else
            lerArquivo("DadosExercicios.txt");
        
        TelaTreino nova = new TelaTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_treinoAppActionPerformed

    private void relatorioAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioAppActionPerformed
        if(dadosDieta.isEmpty())
            preencherDadosDieta();
        else
            lerArquivo("DadosDieta.txt");
        
        if(dadosTreino.isEmpty())
            preencherDadosTreino();
        else
            lerArquivo("DadosTreino.txt");
        
        if(dadosUsuario.isEmpty())
            preencherDadosUsuario();
        else
            lerArquivo("DadosUsuario.txt");
        
        TelaRelatorio nova = new TelaRelatorio();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_relatorioAppActionPerformed

    private void alimentacaoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentacaoAppActionPerformed
        if(dadosDieta.isEmpty())
            preencherDadosDieta();
        else
            lerArquivo("DadosDieta.txt");
        
        TelaAlimentacao nova = new TelaAlimentacao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_alimentacaoAppActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSelecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alimentacaoApp;
    private javax.swing.JButton atualizarDadosApp;
    private javax.swing.JLabel iconeInicio;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JButton relatorioApp;
    private javax.swing.JButton treinoApp;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}
