package Aplicativo;

import java.awt.Color;
import javax.swing.ImageIcon;

public class TelaAlimentacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlimentacao
     */
    
    public TelaAlimentacao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeAlimentacao = new javax.swing.JLabel();
        almocoApp = new javax.swing.JButton();
        lancheTardeApp = new javax.swing.JButton();
        cafeManhaApp = new javax.swing.JButton();
        jantarApp = new javax.swing.JButton();
        voltarApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alimentação");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));

        iconeAlimentacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeAlimentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroAlimentos.png"))); // NOI18N

        almocoApp.setBackground(new java.awt.Color(218, 51, 104));
        almocoApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        almocoApp.setForeground(new java.awt.Color(255, 255, 255));
        almocoApp.setText("Almoço");
        almocoApp.setBorder(null);
        almocoApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        almocoApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                almocoAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                almocoAppMouseExited(evt);
            }
        });
        almocoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almocoAppActionPerformed(evt);
            }
        });

        lancheTardeApp.setBackground(new java.awt.Color(218, 51, 104));
        lancheTardeApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lancheTardeApp.setForeground(new java.awt.Color(255, 255, 255));
        lancheTardeApp.setText("Lanche da tarde");
        lancheTardeApp.setBorder(null);
        lancheTardeApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lancheTardeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lancheTardeAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lancheTardeAppMouseExited(evt);
            }
        });
        lancheTardeApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancheTardeAppActionPerformed(evt);
            }
        });

        cafeManhaApp.setBackground(new java.awt.Color(218, 51, 104));
        cafeManhaApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        cafeManhaApp.setForeground(new java.awt.Color(255, 255, 255));
        cafeManhaApp.setText("Café da manhã");
        cafeManhaApp.setBorder(null);
        cafeManhaApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cafeManhaApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cafeManhaAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cafeManhaAppMouseExited(evt);
            }
        });
        cafeManhaApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeManhaAppActionPerformed(evt);
            }
        });

        jantarApp.setBackground(new java.awt.Color(218, 51, 104));
        jantarApp.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jantarApp.setForeground(new java.awt.Color(255, 255, 255));
        jantarApp.setText("Jantar");
        jantarApp.setBorder(null);
        jantarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jantarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jantarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jantarAppMouseExited(evt);
            }
        });
        jantarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jantarAppActionPerformed(evt);
            }
        });

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeAlimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jantarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cafeManhaApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lancheTardeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(almocoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(iconeAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cafeManhaApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(almocoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lancheTardeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jantarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void almocoAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almocoAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        almocoApp.setForeground(rosaClaro);
        almocoApp.setBackground(white);
    }//GEN-LAST:event_almocoAppMouseEntered

    private void almocoAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almocoAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        almocoApp.setForeground(white);
        almocoApp.setBackground(rosaClaro);
    }//GEN-LAST:event_almocoAppMouseExited

    private void almocoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almocoAppActionPerformed
        TelaRefeicao nova = new TelaRefeicao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeAlmoco.png");
        nova.setParametros("Almoço", icone);
        dispose();
    }//GEN-LAST:event_almocoAppActionPerformed

    private void lancheTardeAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lancheTardeAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        lancheTardeApp.setForeground(rosaClaro);
        lancheTardeApp.setBackground(white);
    }//GEN-LAST:event_lancheTardeAppMouseEntered

    private void lancheTardeAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lancheTardeAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        lancheTardeApp.setForeground(white);
        lancheTardeApp.setBackground(rosaClaro);
    }//GEN-LAST:event_lancheTardeAppMouseExited

    private void lancheTardeAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancheTardeAppActionPerformed
        TelaRefeicao nova = new TelaRefeicao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeLanche.png");
        nova.setParametros("Lanche da Tarde", icone);
        dispose();
    }//GEN-LAST:event_lancheTardeAppActionPerformed

    private void cafeManhaAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeManhaAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        cafeManhaApp.setForeground(rosaClaro);
        cafeManhaApp.setBackground(white);
    }//GEN-LAST:event_cafeManhaAppMouseEntered

    private void cafeManhaAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeManhaAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        cafeManhaApp.setForeground(white);
        cafeManhaApp.setBackground(rosaClaro);
    }//GEN-LAST:event_cafeManhaAppMouseExited

    private void cafeManhaAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeManhaAppActionPerformed
        TelaRefeicao nova = new TelaRefeicao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeCafe.png");
        nova.setParametros("Café da manhã", icone);
        dispose();        
    }//GEN-LAST:event_cafeManhaAppActionPerformed

    private void jantarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jantarAppMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        jantarApp.setForeground(rosaClaro);
        jantarApp.setBackground(white);
    }//GEN-LAST:event_jantarAppMouseEntered

    private void jantarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jantarAppMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        jantarApp.setForeground(white);
        jantarApp.setBackground(rosaClaro);
    }//GEN-LAST:event_jantarAppMouseExited

    private void jantarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jantarAppActionPerformed
        TelaRefeicao nova = new TelaRefeicao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeJanta.png");
        nova.setParametros("Jantar", icone);
        dispose();
    }//GEN-LAST:event_jantarAppActionPerformed

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaSelecao nova = new TelaSelecao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almocoApp;
    private javax.swing.JButton cafeManhaApp;
    private javax.swing.JLabel iconeAlimentacao;
    private javax.swing.JButton jantarApp;
    private javax.swing.JButton lancheTardeApp;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}
