package Aplicativo;

import java.awt.Color;
import javax.swing.ImageIcon;

public class TelaTreino extends javax.swing.JFrame {

    /**
     * Creates new form TelaTreino
     */
    
    public TelaTreino() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeTreino = new javax.swing.JLabel();
        botaoPeitoral = new javax.swing.JButton();
        botaoAbdomen = new javax.swing.JButton();
        botaoBracos = new javax.swing.JButton();
        botaoPernas = new javax.swing.JButton();
        botaoCostaOmbro = new javax.swing.JButton();
        voltarApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Treino");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));

        iconeTreino.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        iconeTreino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeTreino.png"))); // NOI18N

        botaoPeitoral.setBackground(new java.awt.Color(218, 51, 104));
        botaoPeitoral.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botaoPeitoral.setForeground(new java.awt.Color(255, 255, 255));
        botaoPeitoral.setText("Peitoral");
        botaoPeitoral.setBorder(null);
        botaoPeitoral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoPeitoralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoPeitoralMouseExited(evt);
            }
        });
        botaoPeitoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPeitoralActionPerformed(evt);
            }
        });

        botaoAbdomen.setBackground(new java.awt.Color(218, 51, 104));
        botaoAbdomen.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botaoAbdomen.setForeground(new java.awt.Color(255, 255, 255));
        botaoAbdomen.setText("Abdômen");
        botaoAbdomen.setBorder(null);
        botaoAbdomen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAbdomenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAbdomenMouseExited(evt);
            }
        });
        botaoAbdomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbdomenActionPerformed(evt);
            }
        });

        botaoBracos.setBackground(new java.awt.Color(218, 51, 104));
        botaoBracos.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botaoBracos.setForeground(new java.awt.Color(255, 255, 255));
        botaoBracos.setText("Braços");
        botaoBracos.setBorder(null);
        botaoBracos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoBracosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoBracosMouseExited(evt);
            }
        });
        botaoBracos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBracosActionPerformed(evt);
            }
        });

        botaoPernas.setBackground(new java.awt.Color(218, 51, 104));
        botaoPernas.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botaoPernas.setForeground(new java.awt.Color(255, 255, 255));
        botaoPernas.setText("Pernas");
        botaoPernas.setBorder(null);
        botaoPernas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoPernasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoPernasMouseExited(evt);
            }
        });
        botaoPernas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPernasActionPerformed(evt);
            }
        });

        botaoCostaOmbro.setBackground(new java.awt.Color(218, 51, 104));
        botaoCostaOmbro.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botaoCostaOmbro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCostaOmbro.setText("Costas e ombros");
        botaoCostaOmbro.setBorder(null);
        botaoCostaOmbro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCostaOmbroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCostaOmbroMouseExited(evt);
            }
        });
        botaoCostaOmbro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCostaOmbroActionPerformed(evt);
            }
        });

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeTreino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(botaoBracos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoPernas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(botaoAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoPeitoral, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCostaOmbro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPeitoral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBracos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPernas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(botaoCostaOmbro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconeTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaSelecao nova = new TelaSelecao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited

    private void botaoAbdomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbdomenActionPerformed
        TelaIniciarTreino nova = new TelaIniciarTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeAbdominal.png");
        nova.setParametros("Abdômen", icone);
        dispose();
    }//GEN-LAST:event_botaoAbdomenActionPerformed

    private void botaoPeitoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPeitoralActionPerformed
        TelaIniciarTreino nova = new TelaIniciarTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeSupino.png");
        nova.setParametros("Peitoral", icone);
        dispose();
    }//GEN-LAST:event_botaoPeitoralActionPerformed

    private void botaoBracosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBracosActionPerformed
        TelaIniciarTreino nova = new TelaIniciarTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeHaltere.png");
        nova.setParametros("Braços", icone);
        dispose();
    }//GEN-LAST:event_botaoBracosActionPerformed

    private void botaoPernasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPernasActionPerformed
        TelaIniciarTreino nova = new TelaIniciarTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeLegPress.png");
        nova.setParametros("Pernas", icone);
        dispose();
    }//GEN-LAST:event_botaoPernasActionPerformed

    private void botaoCostaOmbroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCostaOmbroActionPerformed
        TelaIniciarTreino nova = new TelaIniciarTreino();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        ImageIcon icone = new ImageIcon("src/Imagens/iconeBarra.png");
        nova.setParametros("Costas e Ombros", icone);
        dispose();
    }//GEN-LAST:event_botaoCostaOmbroActionPerformed

    private void botaoAbdomenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAbdomenMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoAbdomen.setForeground(rosaClaro);
        botaoAbdomen.setBackground(white);
    }//GEN-LAST:event_botaoAbdomenMouseEntered

    private void botaoAbdomenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAbdomenMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoAbdomen.setForeground(white);
        botaoAbdomen.setBackground(rosaClaro);
    }//GEN-LAST:event_botaoAbdomenMouseExited

    private void botaoPeitoralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPeitoralMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoPeitoral.setForeground(rosaClaro);
        botaoPeitoral.setBackground(white);
    }//GEN-LAST:event_botaoPeitoralMouseEntered

    private void botaoPeitoralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPeitoralMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoPeitoral.setForeground(white);
        botaoPeitoral.setBackground(rosaClaro);
    }//GEN-LAST:event_botaoPeitoralMouseExited

    private void botaoBracosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBracosMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoBracos.setForeground(rosaClaro);
        botaoBracos.setBackground(white);
    }//GEN-LAST:event_botaoBracosMouseEntered

    private void botaoBracosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBracosMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoBracos.setForeground(white);
        botaoBracos.setBackground(rosaClaro);
    }//GEN-LAST:event_botaoBracosMouseExited

    private void botaoPernasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPernasMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoPernas.setForeground(rosaClaro);
        botaoPernas.setBackground(white);
    }//GEN-LAST:event_botaoPernasMouseEntered

    private void botaoPernasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPernasMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoPernas.setForeground(white);
        botaoPernas.setBackground(rosaClaro);
    }//GEN-LAST:event_botaoPernasMouseExited

    private void botaoCostaOmbroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCostaOmbroMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoCostaOmbro.setForeground(rosaClaro);
        botaoCostaOmbro.setBackground(white);
    }//GEN-LAST:event_botaoCostaOmbroMouseEntered

    private void botaoCostaOmbroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCostaOmbroMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        botaoCostaOmbro.setForeground(white);
        botaoCostaOmbro.setBackground(rosaClaro);
    }//GEN-LAST:event_botaoCostaOmbroMouseExited

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbdomen;
    private javax.swing.JButton botaoBracos;
    private javax.swing.JButton botaoCostaOmbro;
    private javax.swing.JButton botaoPeitoral;
    private javax.swing.JButton botaoPernas;
    private javax.swing.JLabel iconeTreino;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}
