package Aplicativo;

import static Aplicativo.Arquivos.buscarDataRefeicao;
import static Aplicativo.Arquivos.capturarDados;
import static Aplicativo.Arquivos.dadosDieta;
import static Aplicativo.Arquivos.dadosTreino;
import java.awt.Color;
import static java.awt.Color.white;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TelaRefeicao extends javax.swing.JFrame {

    /**
     * Creates new form TelaRefeicao
     */
    
    public TelaRefeicao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        iconeRefeicao = new javax.swing.JLabel();
        nomeRefeicaoApp = new javax.swing.JLabel();
        cadastrarRefeicao = new javax.swing.JButton();
        dataTreino = new javax.swing.JLabel();
        dataRefeicaoApp = new javax.swing.JFormattedTextField();
        voltarApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Refeição");
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(18, 18, 75));

        iconeRefeicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeRefeicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeCafe.png"))); // NOI18N

        nomeRefeicaoApp.setBackground(new java.awt.Color(255, 255, 255));
        nomeRefeicaoApp.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        nomeRefeicaoApp.setForeground(new java.awt.Color(255, 255, 255));
        nomeRefeicaoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeRefeicaoApp.setText("Café da manhã");
        nomeRefeicaoApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomeRefeicaoAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomeRefeicaoAppMouseExited(evt);
            }
        });

        cadastrarRefeicao.setBackground(new java.awt.Color(218, 51, 104));
        cadastrarRefeicao.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        cadastrarRefeicao.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarRefeicao.setText("Cadastrar");
        cadastrarRefeicao.setBorder(null);
        cadastrarRefeicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarRefeicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarRefeicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarRefeicaoMouseExited(evt);
            }
        });
        cadastrarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarRefeicaoActionPerformed(evt);
            }
        });

        dataTreino.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        dataTreino.setForeground(new java.awt.Color(255, 255, 255));
        dataTreino.setText("Data da Refeição:");

        dataRefeicaoApp.setBackground(new java.awt.Color(255, 255, 255));
        dataRefeicaoApp.setForeground(new java.awt.Color(18, 18, 75));
        try {
            dataRefeicaoApp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataRefeicaoApp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataRefeicaoApp.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        voltarApp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        voltarApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAntes.png"))); // NOI18N
        voltarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarAppMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconeRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomeRefeicaoApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastrarRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelGeralLayout.createSequentialGroup()
                                .addComponent(dataTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataRefeicaoApp)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(iconeRefeicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeRefeicaoApp)
                .addGap(19, 19, 19)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataRefeicaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastrarRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(voltarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeRefeicaoAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeRefeicaoAppMouseEntered
        Color salmao = new Color(218,51,104);
        nomeRefeicaoApp.setForeground(salmao);
    }//GEN-LAST:event_nomeRefeicaoAppMouseEntered

    private void nomeRefeicaoAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeRefeicaoAppMouseExited
        nomeRefeicaoApp.setForeground(white);
    }//GEN-LAST:event_nomeRefeicaoAppMouseExited

    private void cadastrarRefeicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarRefeicaoMouseEntered
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        cadastrarRefeicao.setForeground(rosaClaro);
        cadastrarRefeicao.setBackground(white);
    }//GEN-LAST:event_cadastrarRefeicaoMouseEntered

    private void cadastrarRefeicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarRefeicaoMouseExited
        Color rosaClaro = new Color(218,51,104);
        Color white = new Color(248,248,255);
        cadastrarRefeicao.setForeground(white);
        cadastrarRefeicao.setBackground(rosaClaro);
    }//GEN-LAST:event_cadastrarRefeicaoMouseExited

    private void cadastrarRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarRefeicaoActionPerformed
        if(dataRefeicaoApp.getText().contains(" ")) {
            JOptionPane.showMessageDialog(null, "O campo data deve ser preenchido corretamente!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LocalDate data1 = null;
        LocalDate data2 = null;
        
        String[] date1 = dataRefeicaoApp.getText().split("/"); 
        int dia1 = parseInt(date1[0]);
        int mes1 = parseInt(date1[1]);
        int ano1 = parseInt(date1[2]);
        
        try{
            data1 = LocalDate.of(ano1, mes1, dia1);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "O campo data deve ser preenchido corretamente!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
        if(dadosDieta.isEmpty()){
            data2 = data1;
        }else{
            data2 = dadosDieta.get(0).getDate();
            for(Alimentacao aux : dadosDieta){
                if(data2.compareTo(aux.getDate()) < 0){
                    data2 = aux.getDate();
                }
            }
        }
        
        if(data1.compareTo(data2) < 0){
            JOptionPane.showMessageDialog(null, "O registro contém uma data maior que a inserida!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        TelaAlimentos nova = new TelaAlimentos();
        String refeicao = nomeRefeicaoApp.getText();
        ImageIcon icone = new ImageIcon("src/Imagens/iconeAlimentos.png");
        if(refeicao.equals("Café da manhã")){
            String labelSuperior = "Alimentos do café da manhã";
            String labelInferior = "Total de calorias do café da manhã";
            nova.setParametros(icone, labelSuperior, labelInferior);
        }else if(refeicao.equals("Almoço")){
            String labelSuperior = "Alimentos do almoço";
            String labelInferior = "Total de calorias do almoço";
            nova.setParametros(icone, labelSuperior, labelInferior);
        }else if(refeicao.equals("Lanche da Tarde")){
            String labelSuperior = "Alimentos do lanche da tarde";
            String labelInferior = "Total de calorias do lanche da tarde";
            nova.setParametros(icone, labelSuperior, labelInferior);
        }else{
            String labelSuperior = "Alimentos do jantar";
            String labelInferior = "Total de calorias do jantar";
            nova.setParametros(icone, labelSuperior, labelInferior);
        }
        
        int i = buscarDataRefeicao(refeicao, dataRefeicaoApp.getText());
        if(i != -1) {
            JOptionPane.showMessageDialog(null, "O registro já contém um "+refeicao+"\npara a data inserida!",
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        capturarDados[0] = refeicao;
        capturarDados[1] = dataRefeicaoApp.getText();
        
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarRefeicaoActionPerformed

    private void voltarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseClicked
        // Salvar arquivo
        TelaAlimentacao nova = new TelaAlimentacao();
        nova.setLocationRelativeTo(null);
        nova.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAppMouseClicked

    private void voltarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseEntered
        ImageIcon voltarAntes = new ImageIcon("src/Imagens/voltarDepois.png");
        voltarApp.setIcon(voltarAntes);
    }//GEN-LAST:event_voltarAppMouseEntered

    private void voltarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAppMouseExited
        ImageIcon voltarDepois = new ImageIcon("src/Imagens/voltarAntes.png");
        voltarApp.setIcon(voltarDepois);
    }//GEN-LAST:event_voltarAppMouseExited
    
    public void setParametros(String nome, ImageIcon icone){
        iconeRefeicao.setIcon(icone);
        nomeRefeicaoApp.setText(nome);
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRefeicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarRefeicao;
    private javax.swing.JFormattedTextField dataRefeicaoApp;
    private javax.swing.JLabel dataTreino;
    private javax.swing.JLabel iconeRefeicao;
    private javax.swing.JLabel nomeRefeicaoApp;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JLabel voltarApp;
    // End of variables declaration//GEN-END:variables
}
